package analisis;

public enum TipoToken {
	CONSTANTE_ENTERA, CADENA_CARACTERES, PARENTESIS_ABIERTOS, PARENTESIS_CERRADOS, 
	SUMA, OP_REL_MENOR, OP_LOG_NEGACION, OP_ASIG_DECREMENTO, IDENTIFICADOR, PALABRA_RESERVADA, 
	LLAVE_ABIERTA, LLAVE_CERRADA, SEPARADOR_COMA, SEPARADOR_PUNTOCOMA, COMILLAS;
}
